dist: trusty
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy3"
matrix:
  include:
  - python: 3.7
    dist: xenial
  - python: 3.8
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
script: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=nexmo setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: XO2oAEnOqsELBQK97RJbS4zipC53RF8wh0uGmZBoDL3JDKbP/dDA7TCYKjV0qh39MsMIAgIIP+CHkTCKOzu9Syh9k/j+Pl0VnteGa3IbNuIXUTF9tkA5gGVN+0y3yYGx3IE/PXSqvVVQheDbi25KLiUdc6nf3hOW7pUReLWS/Sg=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
